import { ArrowRight, ArrowUpRight, CheckCircle, Play, FileText, Truck, Wrench, ArrowLeft } from '@phosphor-icons/react';
import { concepts, money } from './model';
import { Brand, Button, Next, Tag } from './UI';

export function Gallery({ choose }) {
  return <main className="gallery"><div className="gallery-top"><Brand onClick={() => window.scrollTo(0,0)}/><Tag>INTERACTIVE DESIGN STUDY</Tag></div><header><p className="eyebrow">ONE OPENING. THREE WAYS IN.</p><h1>A big beginning.<br/><span>Pick your point of view.</span></h1><p>Three complete, clickable directions for OpeningOS.<br/>The same café. The same decisions. A very different feeling.</p></header><div className="concept-grid">{concepts.map((concept,index) => <button key={concept.id} className={`concept-card ${concept.id}`} onClick={() => choose(concept.id)}><div className="concept-art">{concept.id === 'scene' ? <img src="/assets/cafe.png" alt="Sunlit isometric café"/> : concept.id === 'workbench' ? <><img src="/assets/workbench.png" alt="Sage purchasing desk"/><div className="mini-paper"><span>Elm Supply</span><p>YOUR NEXT CHAPTER</p><strong>€7,950</strong><hr/>Everything, considered.</div></> : <><div className="mini-route-head">The real price.</div><div className="mini-cost"><span>€7,950</span><ArrowRight/><span>All in.</span></div><img className="mini-machine" src="/assets/machine.png" alt="Commercial espresso machine"/></>}</div><div className="concept-caption"><span className="number">0{index+1}</span><div><h2>{concept.name}</h2><p>{index===0?'Spatial, warm, connected.':index===1?'Precise, graphic, transparent.':'Tactile, editorial, human.'}</p></div><ArrowUpRight size={25}/></div></button>)}</div><footer><span>Frontend prototypes · fictional suppliers · no purchases or messages</span><span>Start anywhere. Switch designs at any point.</span></footer></main>;
}

export function Landing({ concept, go, start, gallery }) {
  const scene = concept.id === 'scene';
  const bench = concept.id === 'workbench';
  return <div className={`landing landing-${concept.id}`}>
    <header className="landing-nav"><Brand onClick={gallery}/><nav aria-label="Landing navigation"><a href="#how-it-works" onClick={event=>{event.preventDefault();document.getElementById('how-it-works').scrollIntoView({behavior:'smooth'});}}>How it works</a><button onClick={gallery}>Explore designs <ArrowUpRight size={15}/></button></nav><Button secondary onClick={start}>Open demo <ArrowRight size={17}/></Button></header>
    <section className="landing-hero">
      <div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> FOR THE PEOPLE OPENING SOMETHING GOOD</p><h1>{concept.title.split('\n').map((line,i)=><span key={line} className={i===1?'accent-text':''}>{line}</span>)}</h1><p className="hero-description">{concept.description}</p><div className="hero-actions"><Next onClick={start}>Try the Northside café demo</Next><button className="text-button" onClick={()=>go('brief')}>Start your own brief <ArrowUpRight size={19}/></button></div><p className="hero-note"><CheckCircle size={16}/> No sign-up. No card. Just a good place to start.</p></div>
      {scene ? <div className="hero-scene"><img src="/assets/cafe.png" alt="Illustrative sunlit café with equipment and seating"/><button className="hero-pin" onClick={start}><span className="status-dot"/><span>One machine. Three ways forward.<small>See your supplier shortlist</small></span><ArrowUpRight size={18}/></button><span className="scene-caption">A place to imagine. Not a measured floor plan.</span></div> : bench ? <div className="hero-workbench"><div className="polaroid"><img src="/assets/machine.png" alt="Unbranded two-group espresso machine"/><strong>A good place to begin.</strong><small>Atlas 2G · your first decision</small></div><div className="landing-paper"><p className="eyebrow">AN OPENING, IN GOOD HANDS</p><h2>Less chasing.<br/>More choosing.</h2><div><CheckCircle/>Quotes you can actually compare.</div><div><CheckCircle/>The small print, brought forward.</div><div><CheckCircle/>Your next move, ready.</div><button onClick={start}>Pull up a chair <ArrowRight/></button></div><span className="yellow-note">Your next chapter starts here.</span></div> : <div className="hero-routes"><div className="route-statement"><span>HEADLINE PRICE</span><strong>€7,500</strong><p>Looks good.<br/>But is that the whole story?</p></div><div className="landing-cost-stop"><Truck size={24}/><span>Delivery</span><strong>+ €600</strong></div><div className="landing-cost-stop"><Wrench size={24}/><span>Installation</span><strong>+ €400</strong></div><button className="route-total" onClick={start}><span>THE REAL TOTAL</span><strong>€8,500</strong><span>Follow every cost <ArrowRight/></span></button><div className="routes-footnote"><FileText size={16}/> Every stop links back to its quote.</div></div>}
    </section>
    <section className="landing-bottom" id="how-it-works"><div><p className="eyebrow">FROM IDEA TO OPENING DAY</p><h2>A clearer way<br/>to get there.</h2></div>{[['01','Tell us what you’re opening.','One short brief. Your equipment, budget and opening date.'],['02','See the full picture.','Comparable prices, missing terms and the evidence behind them.'],['03','Make your next move.','Ask a supplier, choose an offer, handle a change. Stay in control.']].map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</section>
    <footer className="landing-footer"><Brand onClick={gallery}/><p>Made for your opening. Useful long after.</p><span>Interactive prototype · simulated data and actions</span></footer>
  </div>;
}
